version: '3.5'
services:
  flame:
    container_name: 'flame'
    environment:
      PASSWORD: 'flame_password'
      PASSWORD_FILE: '/run/secrets/password'
    image: 'registry.ipv6.docker.com/pawelmalak/flame:latest'
    network_mode: 'bridge'
    ports:
      - '127.0.0.1:8080:5005'
    restart: 'unless-stopped'
    secrets:
      - 'password'
    volumes:
      - '/opt/flame/:/app/data'
  watchtower:
    container_name: 'watchtower'
    environment:
      TZ: 'Etc/UTC'
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: false
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_REVIVE_STOPPED: true
      WATCHTOWER_POLL_INTERVAL: 86400
      WATCHTOWER_TIMEOUT: 16
    image: 'registry.ipv6.docker.com/containrrr/watchtower:latest'
    network_mode: 'bridge'
    restart: 'unless-stopped'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
secrets:
  password:
    file: '/opt/flame_key'