version: "3.5"
# Ports: 7396 , 36330

services:
  foldingathome:
    container_name: 'foldingathome'
    environment:
      PUID: 0
      PGID: 0
      TZ: 'Etc/UTC'
    image: 'registry.ipv6.docker.com/linuxserver/foldingathome:latest'
    network_mode: 'host'
    restart: 'unless-stopped'
    volumes:
      - '/opt/:/config'