version: '3.5'
services:
  uptime-kuma:
    container_name: 'uptime-kuma'
    environment:
      - 'PUID=0'
      - 'PGID=0'
      - 'TZ=Etc/UTC'
    image: 'registry.ipv6.docker.com/louislam/uptime-kuma:latest'
    network_mode: 'host' #port = 3001
    restart: 'unless-stopped'
    volumes:
      - '/opt/uptime-kuma:/app/data'
  gotify:
    container_name: 'gotify'
    environment:
      GOTIFY_DEFAULTUSER_PASS: ''
    image: 'registry.ipv6.docker.com/gotify/server:latest'
    network_mode: 'bridge'
    restart: 'unless-stopped'
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - '/opt/gotify:/app/data'
  watchtower:
    container_name: 'watchtower'
    environment:
      TZ: 'Etc/UTC'
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: false
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_REVIVE_STOPPED: true
      WATCHTOWER_POLL_INTERVAL: 86400
      WATCHTOWER_TIMEOUT: 16
    image: 'registry.ipv6.docker.com/containrrr/watchtower:latest'
    network_mode: 'host'
    restart: 'unless-stopped'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'