version: '3.3'
# https://github.com/louislam/uptime-kuma
# Port = 3001

services:
  uptime-kuma:
    container_name: 'uptime-kuma'
    hostname: 'uptime-kuma'
    environment:
      - 'PUID=0'
      - 'PGID=0'
      - 'TZ=Etc/UTC'
    image: 'registry.ipv6.docker.com/louislam/uptime-kuma:latest'
    network_mode: 'host'
    restart: 'unless-stopped'
    volumes:
      - '/opt:/app/data'
  watchtower:
    container_name: 'watchtower'
    environment:
      TZ: 'Etc/UTC'
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_REMOVE_VOLUMES: false
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_REVIVE_STOPPED: true
      WATCHTOWER_POLL_INTERVAL: 86400
      WATCHTOWER_TIMEOUT: 16
    image: 'containrrr/watchtower:latest'
    network_mode: 'host'
    restart: 'unless-stopped'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'