version: '3.8'

services:
  postgres:
    container_name: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DATABASE: 'postgres'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    image: 'registry.ipv6.docker.com/library/postgres:15'
    restart: 'unless-stopped'
    volumes:
      - '/var/lib/postgresql/data:/var/lib/postgresql/data'

  zipline:
    container_name: 'zipline'
    environment:
      MFA_TOTP_ENABLED: true
      WEBSITE_SHOW_FILES_PER_USER: true
      WEBSITE_TITLE: 'zipline'
      CORE_RETURN_HTTPS: false
      CORE_SECRET: 'C9dde56j8fCWLo9000XcgW'
      CORE_HOST=: 0.0.0.0
      CORE_PORT: 3000
      CORE_DATABASE_URL: 'postgres://postgres:postgres@postgres/postgres'
      CORE_LOGGER: true
    image: 'registry.ipv6.docker.com/diced/zipline'
    ports:
      - '3000:3000' # only for testing
      #- '127.0.0.1:3000:3000'
    restart: 'unless-stopped'
    volumes:
      - '/docker/zipline/uploads:/zipline/uploads'
      - '/docker/zipline/public:/zipline/public'
    depends_on:
      - 'postgres'