version: '3.8'

name: 'portainer-ce'

networks:
  proxy_network:
    external: true
  backend:
    external: true

services:
  portainer-ce:
    container_name: 'portainer'
    environment:
      TZ: 'UTC'
    hostname: 'portainer'
    image: 'registry.ipv6.docker.com/portainer/portainer-ce:latest'
    networks:
      - 'proxy_network'
    ports:
      - '8000:8000'
      - '9443:9443'
    restart: 'unless-stopped'
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  portainer_data:
    external: true